# Site settings
title: Belgian Rails Girls Guide
description: Rails Girls Guide for Belgian Chapter.
twitter_username: RailsGirls_BE
github_username:  railsgirls-be
baseurl: /railsgirls_guide

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title
